[turso]
url = "https://genderreveal-mpburton.aws-us-east-2.turso.io"
auth_token = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3Nzg0NDE3NjAsImlkIjoiMDE5ZTEzNjMtMTAwMS03ODk5LWI3NDMtMDUxNTM1MDRiNTM0IiwicmlkIjoiNjFmYzlhNjUtNWM3Zi00YzQxLWE1ZWItMDM3NjM1YjFiMDE5In0.1hleSvCXggP27geWBiBF8laoL1caffrwNypJVdjgeXoAOzO8n_3vYU63eSeuw-j-D7wXN9KxLE7eNqX3tanlDA"
